### ISSUE TITLE
平台已经改版，代码需要更新了，报错了。

### ISSUE THREAD

**Issue by charwavid** [sxchou/douyin#1]
(douyin) C:\douyin>python v6.py
Traceback (most recent call last):
  File "v6.py", line 97, in <module>
    run()
  File "v6.py", line 82, in run
    room_id, room_title, room_user_count, wss_url, ttwid = fetch_live_room_info(web_url)
  File "v6.py", line 20, in fetch_live_room_info
    data_string = re.findall(r'<script id="RENDER_DATA" type="application/json">(.*?)</script>', res.text)[0]
IndexError: list index out of range

平台已经改版，代码需要更新了，报错了。

**Comment by sxchou** [comment]
工作忙，没时间更新代码了。不能用就去找找别的资源吧，抱歉
